# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Requester HTTP Client Documentation"
email: kylebebak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Searchable Docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://requester.org" # the base hostname & protocol for your site
twitter_username: KyleBebak
github_username: kylebebak
# no date or extension in url
permalink: /post/:title
home: "http://requester.org"
github_url: "https://github.com/kylebebak/Requester"
youtube_url: "https://www.youtube.com/watch?v=kVO5AWIsmF0"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude: [Gemfile, Gemfile.lock, tutorial.pyr, build.py, toc.py]

gems:
  - jekyll-seo-tag
